monitor.bluez.properties = {
  bluez5.roles = [ a2dp_sink ]
}

monitor.bluez.rules = [
  {
    matches = [
      { node.name = "~bluez_input.*" }
    ]
    actions = {
      update-props = {
        bluez5.media-source-role = "playback"
        node.pause-on-idle = false
      }
    }
  }
]
